# Generated by Django 4.1 on 2024-02-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surf_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='relative_humidity_2m',
            new_name='wind_direction_10m',
        ),
    ]
